### ISSUE TITLE
Crash on empty drive

### ISSUE THREAD

**Issue by HaraldBecherer** [CHDKUtil/CHIMP#1]
[ChdkUtility-20170618.zip](https://github.com/CHDKUtil/CHIMP/files/1083073/ChdkUtility-20170618.zip)

Hi Dmitrys
I just tried CHIMP. Cool! Thanks a lot for it!
On my laptop with build in SD card reader it workt 100%
On my my desktop there is an external card reader connected over USB with 3 drives.
When there is a drive without any card in it (usualy there is only one in) CHIMP crashes with:
System.IO.FileNotFoundException: The device is not ready
Maybe there is a way to detect empty drives?

Greetings,

Harald

**Comment by dmitry-shechtman** [comment]
Thank you for your feedback.

Please try the attached version to see if it works (both with and without a card in the USB reader).

**Edit 2017-06-19:** Removed the attachment.

**Comment by HaraldBecherer** [comment]
Fantastic. Everything works for me:-)
My G15 boots and work.
Now I can use the same card to install the fresh alpha for the G16 (manualy).
It makes the task to install the CHDK very easy.
The wizard is well thought through.
Thank you very much!

Greetings,

Harald

[ChdkUtility-20170619.zip](https://github.com/CHDKUtil/CHIMP/files/1085616/ChdkUtility-20170619.zip)
