### ISSUE TITLE
Disk.GetDeviceName() crash on pCloud drive

### ISSUE THREAD

**Issue by alismatales** [CHDKUtil/CHIMP#3]
I have a pCloud storage account which maps the storage as a drive to your computer. CHIMP crashes immediately when it checks for sdcards, as long as the drive is mapped: 

> 
2018-02-12T15:39:40.0234140+01:00  [VRB] Entering "Card" (b93f6593)
2018-02-12T15:39:40.0546390+01:00  [VRB] Detecting cards (10dcce48)
2018-02-12T15:39:40.1097543+01:00  [INF] Detected {"DeviceId":"\\\\?\\Volume{c6729ed9-3c03-11e7-af3a-5453edb6a239}\\","DriveLetter":"P:","Label":"pCloud Drive","FileSystem":"exFAT","Capacity":2199023255552,"FreeSpace":1771341754368} (3b5ca34b)
2018-02-12T15:39:40.1407727+01:00  [FTL] System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Runtime.InteropServices.COMException: Unzulässige Funktion. (Ausnahme von HRESULT: 0x80070001)
   bei Chimp.Disk.GetDeviceName() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Disk.cs:Zeile 60.
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei Chimp.Disk.GetDiskParams(UInt32& sectorSize, UInt64& driveSectors, UInt64& diskSize) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Disk.cs:Zeile 28.
   bei Chimp.Disk..ctor(Volume volume) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Disk.cs:Zeile 17.
   bei Chimp.Volume.GetDisk() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Volume.cs:Zeile 33.
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei Chimp.Services.PartitionService.GetPartitionTypes(String driveLetter) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Services\PartitionService.cs:Zeile 122.
   bei Chimp.Controllers.CardController.CreateCardItem(CardInfo card) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\CardController.cs:Zeile 202.
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   bei Chimp.Controllers.CardController.CreateViewModel() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\CardController.cs:Zeile 117.
   bei Chimp.Controllers.CardController.Initialize() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\CardController.cs:Zeile 45.
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Chimp.Controllers.Controller`1.OnInitialized(Task task) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\Controller.cs:Zeile 43.
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Chimp.Controllers.Controller`1.<InitializeAsync>d__3.MoveNext() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\Controller.cs:Zeile 31.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Chimp.Containers.ControllerContainer.<CreateControllerAsync>d__7.MoveNext() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Containers\ControllerContainer.cs:Zeile 45.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Chimp.Containers.ControllerContainer.<GetControllerAsync>d__6.MoveNext() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Containers\ControllerContainer.cs:Zeile 34.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Chimp.MainWindow.<OnSelectedIndexChangedAsync>d__35.MoveNext() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\MainWindow.xaml.cs:Zeile 202.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Chimp.MainWindow.<Step_PropertyChanged>d__24.MoveNext() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\MainWindow.xaml.cs:Zeile 87.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Interne Ausnahme #0) System.Runtime.InteropServices.COMException (0x80070001): Unzulässige Funktion. (Ausnahme von HRESULT: 0x80070001)
   bei Chimp.Disk.GetDeviceName() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Disk.cs:Zeile 60.
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei Chimp.Disk.GetDiskParams(UInt32& sectorSize, UInt64& driveSectors, UInt64& diskSize) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Disk.cs:Zeile 28.
   bei Chimp.Disk..ctor(Volume volume) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Disk.cs:Zeile 17.
   bei Chimp.Volume.GetDisk() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Volume.cs:Zeile 33.
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei Chimp.Services.PartitionService.GetPartitionTypes(String driveLetter) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Services\PartitionService.cs:Zeile 122.
   bei Chimp.Controllers.CardController.CreateCardItem(CardInfo card) in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\CardController.cs:Zeile 202.
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   bei Chimp.Controllers.CardController.CreateViewModel() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\CardController.cs:Zeile 117.
   bei Chimp.Controllers.CardController.Initialize() in C:\Users\Dmitry\Documents\GitHub\CHDKUtil\CHIMP\src\CHIMP\CHIMP\Controllers\CardController.cs:Zeile 45.
   bei System.Threading.Tasks.Task.Execute()<---
 (888381fe)
2018-02-12T15:39:41.0297301+01:00  [VRB] Leaving "Card" (d90f1dd5)
2018-02-12T15:39:41.0327338+01:00  [VRB] Detecting cards (10dcce48)
2018-02-12T15:39:41.0412374+01:00  [INF] Exit code: -2146233088 (33024a0b)
2018-02-12T15:39:41.0412374+01:00  [INF] 
 (c290f677)

**Comment by dmitry-shechtman** [comment]
Thank you for reporting this issue.

Please add the log file as an attachment in your first post.

Thanks
