### ISSUE TITLE
HowTo: compile application

### ISSUE THREAD

**Issue by KiberInfinity** [CHDKUtil/CHIMP#4]
In release section I found only  ZIP with sources, without binary application.

Please add to README.md how to build application :

1) Download and unpack CHIMP sources (remember this path as <chimp_unpack_path>).

2) Download and install  "Build Tools for Visual Studio 2017" (expand spoiler "Tools for Visual Studio 2017" on download page for see it) 
https://visualstudio.microsoft.com/downloads/

3) Download Nuget binary to <chimp_unpack_path>\CHIMP-0.x.x\src\CHIMP\CHIMP\ 
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe 
or from any link on  https://www.nuget.org/downloads

4) Open installed "Visual Studio 2017 Developer Command Prompt" and run following commands:
```batch
cd <chimp_unpack_path>\CHIMP-0.x.x\src\CHIMP\CHIMP
nuget install -OutputDirectory ..\packages
msbuild /property:Configuration=Release;OutputPath=bin\Release\ CHIMP.csproj
```
5) Run and use compiled CHIMP application:
CHIMP-0.x.x\src\CHIMP\CHIMP\bin\Release\CHIMP.exe

**Comment by dmitry-shechtman** [comment]
Thank you for your feedback.

It looks like you opened the Releases section from a mobile browser. The desktop version shows CHIMP-0.9.5.zip, which contains the binary.

Closing for now.
