### ISSUE TITLE
Aborts with USB reader

### ISSUE THREAD

**Issue by lietusme** [CHDKUtil/CHIMP#5]
CHIMP is unable to format and install CHDK because it aborts with "Card must be locked" error

![image](https://user-images.githubusercontent.com/10194949/61595679-dda4fc00-ac02-11e9-8623-14f9126909aa.png)

I'm using USB SD card reader and it does not check for card being locked. IMO CHIMP should just warn about this but not error and abort...

**Comment by dmitry-shechtman** [comment]
CHIMP has been successfully tested to work with such SD readers.

The screenshot indicates an aborted installation (probably for unrelated reasons). The message shown is in fact a warning pertaining to **CHDK** operation.

Closing.

**Comment by lietusme** [comment]
This still makes it unusable, as it aborts installation. How to investigate what is causing this then?

**Comment by dmitry-shechtman** [comment]
Please attach a detailed log as per the instructions provided here:

https://chdk.setepontos.com/index.php?topic=13091.0
